export const COLORS = new Map([
    ["J", { color: "#fff", background: "#D6336C" }],
    ["C", { color: "#fff", background: "#228BE6" }],
    ["D", { color: "#fff", background: "#FFB819" }],
    ["M", { color: "#fff", background: "#AE3EC9" }],
    ["K", { color: "#fff", background: "#11A97B" }],
    ["N", { color: "#fff", background: "#F76707" }],
    ["F", { color: "#11899B", background: "#99E9F2" }],
    ["G", { color: "#A5214F", background: "#F783AC" }],
    ["Y", { color: "#B57D00", background: "#FFEC99" }],
    ["Z", { color: "#2A893B", background: "#8CE99A" }],
    ["P", { color: "#774DF6", background: "#D0BFFF" }],
    ["X", { color: "#BF4F05", background: "#FFC078" }],
    ["S", { color: "#fff", background: "#14A3B8" }],
    ["A", { color: "#fff", background: "#E03131" }],
    ["E", { color: "#fff", background: "#845EF7" }],
    ["R", { color: "#fff", background: "#34AA49" }],
    ["T", { color: "#9831B1", background: "#E599F7" }],
    ["W", { color: "#1778CD", background: "#A5D8FF" }],
    ["V", { color: "#588B11", background: "#C0EB75" }],
    ["L", { color: "#fff", background: "#4C6EF5" }],
    ["H", { color: "#B01B1B", background: "#FF8787" }],
    ["I", { color: "#0F916A", background: "#96F2D7" }],
    ["Q", { color: "#fff", background: "#AC743B" }],
    ["B", { color: "#fff", background: "#68A514" }],
    ["O", { color: "#3E62F4", background: "#BAC8FF" }],
    ["U", { color: "#fff", background: "#8893A0" }],
])
